DROP VIEW "main"."VistaMedia";
CREATE VIEW VistaMedia AS
SELECT 
    M.TITLE,
    M.YEAR,
    D.NAME AS ARTIST,
    P.NAME AS HOUSE,
    T.NAME AS CATEGORY
FROM 
    MEDIA as M
LEFT JOIN DIRECTORES as D ON M.ID_ARTST = D.ID_ARTST
LEFT JOIN PRODUCTORAS as P ON M.ID_HOUSE = P.ID_HOUSE
LEFT JOIN TYPE as T ON M.ID_CATEG = T.ID_CATEG
WHERE 
    M.SEEN = 1